# Generated by Django 4.0.3 on 2022-04-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userlogin',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('id', models.IntegerField(default=0)),
                ('number', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
