# Generated by Django 4.0.3 on 2022-04-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_userlogin_pass1_userlogin_pass2'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='image',
            field=models.ImageField(default='NO IMAGE', max_length=1, upload_to=None),
        ),
        migrations.AddField(
            model_name='userlogin',
            name='role',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
