# Generated by Django 4.0.3 on 2022-04-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_userlogin_image_userlogin_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='image',
            field=models.ImageField(default='NO IMAGE', max_length=150, upload_to=None),
        ),
    ]
