# Generated by Django 4.0.3 on 2022-04-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_userlogin_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlogin',
            old_name='name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty'), ('Admin Officer', 'Admin officer'), ('Non Faculty Teacher', 'Non Faculty Teacher'), ('Admin', 'admin'), ('Helper', 'Helper')], default='Student', max_length=50),
        ),
    ]
