# Generated by Django 4.0.3 on 2022-04-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_name_userlogin_username_alter_userlogin_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlogin',
            old_name='username',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='number',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
