# Generated by Django 4.0.3 on 2022-04-17 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_username_userlogin_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogin',
            name='image',
        ),
    ]
