# Generated by Django 4.0.3 on 2022-04-17 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_userlogin_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogin',
            name='pass1',
        ),
        migrations.RemoveField(
            model_name='userlogin',
            name='pass2',
        ),
    ]
