# Generated by Django 4.0.3 on 2022-04-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_userlogin_pass1_remove_userlogin_pass2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='role',
            field=models.CharField(max_length=50),
        ),
    ]
