# Generated by Django 4.0.3 on 2022-04-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_userlogin_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
