# Generated by Django 4.0.3 on 2022-04-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_userlogin_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='image',
            field=models.ImageField(default='no image', upload_to='userImages'),
        ),
    ]
