# Generated by Django 4.0.3 on 2022-05-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_userlogin_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lodgerid', models.IntegerField(default=0)),
                ('Perpenetrers', models.CharField(max_length=250)),
                ('reviewer', models.IntegerField(default=0)),
                ('reason', models.CharField(max_length=1000)),
                ('image', models.ImageField(default='no image', upload_to='complainImages')),
            ],
        ),
    ]
