# Generated by Django 4.0.3 on 2022-05-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_lodgerid_complains_lodger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complains',
            name='comment',
            field=models.CharField(default=' ', max_length=250),
        ),
        migrations.AddField(
            model_name='complains',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
