# Generated by Django 4.0.3 on 2022-05-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_complains_comment_complains_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='image2',
            field=models.ImageField(default='no image', upload_to='userImages'),
        ),
    ]
